invoices-app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations
  resources :invoices
  resources :bookings
  resources :users

  mount Crono::Web, at: '/crono'

end

invoices-app/app/models/booking.rb
require('active_record')
require('active_support')

class Booking  < ActiveRecord::Base

  def to_s
    return "(#{organization}) Booking #{book_number} for #{amount} from #{supplier}"
  end


end

invoices-app/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params[:booking]
    end
end

invoices-app/app/helpers/bookings_helper.rb
module BookingsHelper
end

invoices-app/app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

invoices-app/app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

invoices-app/app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<% @bookings.each do |booking| %>
  <row>
    <div class="small-8"><%= booking %></div>
    <div class="small-4">
      <ul class="small-block-grid-3">
        <li><%= link_to 'Show', booking, class: 'button tiny' %></li>
        <li><%= link_to 'Edit', edit_booking_path(booking), class: 'button tiny' %></li>
        <li><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny' %></li>
      </ul>
    </div>
  </row>
<% end %>
<br>

invoices-app/app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

invoices-app/app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>