invoices-app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations
  resources :invoices
  resources :bookings
  resources :users

  mount Crono::Web, at: '/crono'

end

invoices-app/app/models/organization.rb
require 'active_record'

class Organization < ActiveRecord::Base

  validates_uniqueness_of :name
  serialize :backends, Array

  def Organization.by_name(organization)
    org=Organization.where(name: organization).first
    return org
  end

  def to_s
    return @name
  end

  def invoices
    Invoice.where(organization: self).order(created_at: :desc).all
  end

end

invoices-app/app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :set_viiper_uploader, only: [:new, :edit]
  load_and_authorize_resource

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @dir_names = @viiper_uploader.all_dir_names
  end

  # GET /organizations/1/edit
  def edit
    @dir_names = @viiper_uploader.all_dir_names
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    def set_viiper_uploader
      @viiper_uploader = ViiperUploader.new({})
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params
        .require(:organization)
        .permit(:name, :default_approver,:viiper_dir_name, backends: [])
    end
end

invoices-app/app/helpers/organizations_helper.rb
module OrganizationsHelper
end

invoices-app/app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-9 columns">
      <%= f.label :name, "Name :" %>
      <%= f.text_field :name %>
    </div>
    <div class="large-3 columns">
      <%= f.label :backends %>
      <%= f.select :backends, [['Jira', 'jira'], ['Oracle', 'viiper']], {}, {multiple: true, size: 2}%>
    </div>
  </div>
  <div class="row">
    <div class="small-6 columns">
      <%= f.label :default_approver, 'Approver :'%>
      <%= f.text_field :default_approver%>
    </div>
    <div class="small-6 columns">
      <%= f.label :viiper_dir_name, 'Viiper Directory Name :'%>
      <%= f.select :viiper_dir_name, @dir_names %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

invoices-app/app/views/organizations/edit.html.erb
<h1>Editing organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

invoices-app/app/views/organizations/index.html.erb
<h1>Listing organizations</h1>

<% @organizations.each do |organization| %>
  <div class="row">
    <div class="small-8 columns"><%= organization.name %></div>

    <div class="small-4 columns">
      <ul class="small-block-grid-3 columns">
        <li><%= link_to 'Show', organization, class: 'button tiny' %></li>
        <li><%= link_to 'Edit', edit_organization_path(organization), class: 'button tiny' %></li>
        <li><%= button_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button tiny' %></li>
      </ul>
    </div>
  </div>
<% end %>

<br>

<%= link_to 'New Organization', new_organization_path %>

invoices-app/app/views/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>

invoices-app/app/views/organizations/show.html.erb
<h1>Organization : <%= @organization.name %></h1>

<% if @organization.backends.member? "jira" %>
  <h2>Jira Backend Enabled</h2>
  <div class="row">
    <div class="small-3 columns">
      Default Approver :
    </div>
    <div class="small-9 columns">
      <%= @organization.default_approver %>
    </div>
  </div>
<% end %>

<% if @organization.backends.member? "viiper" %>
  <h2>Viiper Backend Enabled</h2>

  <div class="row">
    <div class="small-3 columns">
      Viiper Directory Name :
    </div>
    <div class="small-9 columns">
      <%= @organization.viiper_dir_name %>
    </div>
  </div>
<% end %>

<br/>

<ul class="small-block-grid-2">
  <li><%= link_to 'Edit', edit_organization_path(@organization), class: 'button' %></li>
  <li><%= link_to 'Back', organizations_path, class: 'button' %></li>
</ul>