invoices-app/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :organizations
  resources :invoices
  resources :bookings
  resources :users

  mount Crono::Web, at: '/crono'

end

invoices-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Invoice Approval Uploader (v#{Rails.application.config.version})" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
      <div class="large-12 columns">
        <div class="large-4 columns">
          <p class="version">
            <%= "(v#{Rails.application.config.version})" %>
          </p>
        </div>

        <div class="nav-bar right">
          <ul class="button-group">
            <li><%= link_to "Home", root_path, class: 'button' %></li>
            <li><%= link_to "Organizations", organizations_path, class: 'button' %></li>
            <li><%= link_to "Invoices", invoices_path, class: 'button' %></li>
            <li><%= link_to "Users", users_path, class: 'button' %></li>
            <li><%= link_to "Jobs", crono_web_path, class: 'button' %>
          </ul>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        <% flash.each do |name, msg| -%>
            <div class="<%= name %>"><%= msg %><a href class="close">x</a></div>
        <% end -%>

        <%= yield %>
      </div>
    </div>
  </body>
</html>